version: "3"
services:
  db-test:
    container_name: db-test
    image: postgres
    restart: always
    ports:
      - 1234:${POSTGRES_PORT}
    working_dir: /app
    command: postgres -p ${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database-test:/var/lib/postgresql/data

  message-broker-test:
    container_name: message-broker-test
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:${RABBITMQ_PORT}
      - 15672:${RABBITMQ_COMUNICATION_PORT}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  solid-test:
    container_name: solid-test
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - 5000:${PORT}
    depends_on:
      - db-test
      - message-broker-test
    working_dir: /app
    command: bash -c "npx prisma migrate dev && npm test"
    env_file:
      - .env.test
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./tsconfig.json:/app/tsconfig.json

volumes:
  database-test:
