version: "3"
services:
  db-development:
    container_name: db-development
    image: postgres
    restart: always
    ports:
      - 1234:${POSTGRES_PORT}
    working_dir: /app
    command: postgres -p ${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data

  message-broker-development:
    container_name: message-broker-development
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:${RABBITMQ_PORT}
      - 15672:${RABBITMQ_COMUNICATION_PORT}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq:/etc/rabbitmq/
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq/

  solid-development:
    container_name: solid-development
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - 5000:${PORT}
    depends_on:
      - db-development
      - message-broker-development
    working_dir: /app
    command: bash -c "npx prisma migrate dev && npm run dev"
    env_file:
      - .env.development
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./tsconfig.json:/app/tsconfig.json

volumes:
  database:
  rabbitmq:
  rabbitmq-data:
  rabbitmq-logs:
