name: PullRequest
on: [ pull_request ]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_PORT: ${{ secrets.PORT }}
          envkey_MAIL_NAME: ${{ secrets.MAIL_NAME }}
          envkey_MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_POSTGRES_PORT: 5432
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_RABBITMQ_PORT: 5672
          envkey_RABBITMQ_COMUNICATION_PORT: 15672
          envkey_RABBITMQ_DEFAULT_USER: ${{ secrets.RABBITMQ_DEFAULT_USER }}
          envkey_RABBITMQ_DEFAULT_PASS: ${{ secrets.RABBITMQ_DEFAULT_PASS }}
          enkey_MESSAGE_BROKER_URI: ${{ secrets.MESSAGE_BROKER_URI }}
          file_name: .env.test
      - name: Run tests
        run: npm run test:docker
